# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_varopts', [dirname(__file__)])
        except ImportError:
            import _varopts
            return _varopts
        if fp is not None:
            try:
                _mod = imp.load_module('_varopts', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _varopts = swig_import_helper()
    del swig_import_helper
else:
    import _varopts
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SVec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVec, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _varopts.SVec_x_set
    __swig_getmethods__["x"] = _varopts.SVec_x_get
    if _newclass:
        x = _swig_property(_varopts.SVec_x_get, _varopts.SVec_x_set)
    __swig_setmethods__["y"] = _varopts.SVec_y_set
    __swig_getmethods__["y"] = _varopts.SVec_y_get
    if _newclass:
        y = _swig_property(_varopts.SVec_y_get, _varopts.SVec_y_set)
    __swig_setmethods__["z"] = _varopts.SVec_z_set
    __swig_getmethods__["z"] = _varopts.SVec_z_get
    if _newclass:
        z = _swig_property(_varopts.SVec_z_get, _varopts.SVec_z_set)

    def __init__(self):
        this = _varopts.new_SVec()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _varopts.delete_SVec
    __del__ = lambda self: None
SVec_swigregister = _varopts.SVec_swigregister
SVec_swigregister(SVec)

class SNtVars(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SNtVars, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SNtVars, name)
    __repr__ = _swig_repr
    __swig_setmethods__["loc"] = _varopts.SNtVars_loc_set
    __swig_getmethods__["loc"] = _varopts.SNtVars_loc_get
    if _newclass:
        loc = _swig_property(_varopts.SNtVars_loc_get, _varopts.SNtVars_loc_set)
    __swig_setmethods__["b_bound"] = _varopts.SNtVars_b_bound_set
    __swig_getmethods__["b_bound"] = _varopts.SNtVars_b_bound_get
    if _newclass:
        b_bound = _swig_property(_varopts.SNtVars_b_bound_get, _varopts.SNtVars_b_bound_set)
    __swig_setmethods__["b_must_bind"] = _varopts.SNtVars_b_must_bind_set
    __swig_getmethods__["b_must_bind"] = _varopts.SNtVars_b_must_bind_get
    if _newclass:
        b_must_bind = _swig_property(_varopts.SNtVars_b_must_bind_get, _varopts.SNtVars_b_must_bind_set)
    __swig_setmethods__["val"] = _varopts.SNtVars_val_set
    __swig_getmethods__["val"] = _varopts.SNtVars_val_get
    if _newclass:
        val = _swig_property(_varopts.SNtVars_val_get, _varopts.SNtVars_val_set)
    __swig_setmethods__["cd"] = _varopts.SNtVars_cd_set
    __swig_getmethods__["cd"] = _varopts.SNtVars_cd_get
    if _newclass:
        cd = _swig_property(_varopts.SNtVars_cd_get, _varopts.SNtVars_cd_set)
    __swig_setmethods__["iext_var"] = _varopts.SNtVars_iext_var_set
    __swig_getmethods__["iext_var"] = _varopts.SNtVars_iext_var_get
    if _newclass:
        iext_var = _swig_property(_varopts.SNtVars_iext_var_get, _varopts.SNtVars_iext_var_set)

    def __init__(self):
        this = _varopts.new_SNtVars()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _varopts.delete_SNtVars
    __del__ = lambda self: None
SNtVars_swigregister = _varopts.SNtVars_swigregister
SNtVars_swigregister(SNtVars)


def fact(n):
    return _varopts.fact(n)
fact = _varopts.fact

def cnt_vars(loc, b_bound, b_must_bind, val, cd, iext_var):
    return _varopts.cnt_vars(loc, b_bound, b_must_bind, val, cd, iext_var)
cnt_vars = _varopts.cnt_vars
# This file is compatible with both classic and new-style classes.

cvar = _varopts.cvar

