# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_varopts', [dirname(__file__)])
        except ImportError:
            import _varopts
            return _varopts
        if fp is not None:
            try:
                _mod = imp.load_module('_varopts', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _varopts = swig_import_helper()
    del swig_import_helper
else:
    import _varopts
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SVec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVec, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _varopts.SVec_x_set
    __swig_getmethods__["x"] = _varopts.SVec_x_get
    if _newclass:
        x = _swig_property(_varopts.SVec_x_get, _varopts.SVec_x_set)
    __swig_setmethods__["y"] = _varopts.SVec_y_set
    __swig_getmethods__["y"] = _varopts.SVec_y_get
    if _newclass:
        y = _swig_property(_varopts.SVec_y_get, _varopts.SVec_y_set)
    __swig_setmethods__["z"] = _varopts.SVec_z_set
    __swig_getmethods__["z"] = _varopts.SVec_z_get
    if _newclass:
        z = _swig_property(_varopts.SVec_z_get, _varopts.SVec_z_set)

    def __init__(self):
        this = _varopts.new_SVec()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _varopts.delete_SVec
    __del__ = lambda self: None
SVec_swigregister = _varopts.SVec_swigregister
SVec_swigregister(SVec)

class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _varopts.new_intArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _varopts.delete_intArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _varopts.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _varopts.intArray___setitem__(self, index, value)

    def cast(self):
        return _varopts.intArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _varopts.intArray_frompointer
    if _newclass:
        frompointer = staticmethod(_varopts.intArray_frompointer)
intArray_swigregister = _varopts.intArray_swigregister
intArray_swigregister(intArray)
cvar = _varopts.cvar

def intArray_frompointer(t):
    return _varopts.intArray_frompointer(t)
intArray_frompointer = _varopts.intArray_frompointer

class charArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, charArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, charArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _varopts.new_charArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _varopts.delete_charArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _varopts.charArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _varopts.charArray___setitem__(self, index, value)

    def cast(self):
        return _varopts.charArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _varopts.charArray_frompointer
    if _newclass:
        frompointer = staticmethod(_varopts.charArray_frompointer)
charArray_swigregister = _varopts.charArray_swigregister
charArray_swigregister(charArray)

def charArray_frompointer(t):
    return _varopts.charArray_frompointer(t)
charArray_frompointer = _varopts.charArray_frompointer


def set_num_vars(hvos, n):
    return _varopts.set_num_vars(hvos, n)
set_num_vars = _varopts.set_num_vars

def set_l_phrases_len(hvos, l_phrases_len, len):
    return _varopts.set_l_phrases_len(hvos, l_phrases_len, len)
set_l_phrases_len = _varopts.set_l_phrases_len

def init_vo(hgg):
    return _varopts.init_vo(hgg)
init_vo = _varopts.init_vo

def cnt_vars(hvos, loc, b_bound, b_must_bind, val, cd, iext_var):
    return _varopts.cnt_vars(hvos, loc, b_bound, b_must_bind, val, cd, iext_var)
cnt_vars = _varopts.cnt_vars

def do_vo(hvos):
    return _varopts.do_vo(hvos)
do_vo = _varopts.do_vo

def free_vo(hvos):
    return _varopts.free_vo(hvos)
free_vo = _varopts.free_vo

def init_capp():
    return _varopts.init_capp()
init_capp = _varopts.init_capp

def set_el_bitvec_size(happ, size):
    return _varopts.set_el_bitvec_size(happ, size)
set_el_bitvec_size = _varopts.set_el_bitvec_size

def free_capp(hcapp):
    return _varopts.free_capp(hcapp)
free_capp = _varopts.free_capp

def init_cgg(hcapp):
    return _varopts.init_cgg(hcapp)
init_cgg = _varopts.init_cgg

def free_gg(hgg):
    return _varopts.free_gg(hgg)
free_gg = _varopts.free_gg

def set_num_els_reps(hgg, num_reps):
    return _varopts.set_num_els_reps(hgg, num_reps)
set_num_els_reps = _varopts.set_num_els_reps

def set_els_rep(hgg, bitvec, hd, iel):
    return _varopts.set_els_rep(hgg, bitvec, hd, iel)
set_els_rep = _varopts.set_els_rep

def set_l_wlist_vars_len(hgg, size):
    return _varopts.set_l_wlist_vars_len(hgg, size)
set_l_wlist_vars_len = _varopts.set_l_wlist_vars_len

def set_l_wlist_var(hgg, varquad, ivar):
    return _varopts.set_l_wlist_var(hgg, varquad, ivar)
set_l_wlist_var = _varopts.set_l_wlist_var
# This file is compatible with both classic and new-style classes.


